### ISSUE TITLE
Feedback Score

### ISSUE THREAD

**Issue by tjoye20** [Adamerz/Colmar_Academy_capstone#1]
### Criteria 1: HTML Structure  
* _Score Level:_ 4 - Exceeds Expectations
* _Comment(s):_ Really clean html file that was easy to follow. 
 
### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 4: Visual Design and Accessibility (Color Palette, Typography, Transitions, etc.)
* _Score Level:_ 4 - Exceeds Expectations
 
### Overall Score: 16/16
You crushed this project, Adam. Really good work on this. You have a really strong grasp of HTML and CSS, along with using media queries for responsive design. Hope you move to the next stage and start learning to build web applications, I'm confident you'll do well there too. Great work!

**Comment by byadambrown** [comment]
Thank you for the encouragement, TJ. I appreciate the feedback and support. I'll be moving onto web applications right away. 

Best Regards, 

Adam
